### ISSUE TITLE
snake segfaults

### ISSUE THREAD

**Issue by dasl-** [dasl-/pifi#26]
perhaps related to vectorized LEDs?

https://gist.github.com/dasl-/6b6073b2604518febc3f7f113f93ed46

If we can't debug it, perhaps we can also just remove the signal handler on sigsegv? https://stackoverflow.com/questions/57651775/python-process-not-responding-with-custom-signal-handler-dealing-with-segmentati

Right now, when segfault happens, it pegs a CPU. Maybe the signal handler is infinite looping?

**Comment by dasl-** [comment]
Since it was a speculative fix, if it recurrs, we should reopen this issue.

**Comment by dasl-** [comment]
This happened again. GDB backtrace:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00132eb8 in ?? ()
(gdb) bt
#0  0x00132eb8 in  ()
#1  0x000b8a0c in PyObject_GetIter ()
#2  0xf2ea805e in  ()
```

Additionally, the unix socket for snake was behaving strangely. It would randomly disconnect / timeout etc. I suspect this was due to me replacing the raspberry pi's USB cable with a different white colored USB cable, which was smaller gauge wire than the original USB cable that I was using. Thus, the pi was getting more frequent undervoltage issues, which manifested in this weird behavior while playing snake. Since replacing the USB cable with the original thicker gauge cable, the issues stopped, although I did not test extensively - that would have required playing hours of snake and waiting for the random issues to recur.
